# Generated by Django 5.2.16 on 2026-07-18 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='file',
            field=models.FileField(help_text='Upload lab result file (PDF, image, or document — max 10MB).', upload_to='lab_results/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'doc', 'docx'])]),
        ),
    ]
