# Generated by Django 5.2.16 on 2026-07-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Comma-separated symptoms selected by patient.')),
                ('predicted_condition', models.CharField(max_length=200)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Percentage confidence score (e.g. 85.50)', max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='patients.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'AI Diagnosis Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField(help_text='Systolic reading (e.g. 120)')),
                ('diastolic', models.IntegerField(help_text='Diastolic reading (e.g. 80)')),
                ('pulse', models.IntegerField(help_text='Heart rate / Pulse rate in bpm')),
                ('device_id', models.CharField(default='Simulator-BLE', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_readings', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
